package Vista;

import Control.MovimientoData;
import Modelo.Movimiento;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariel
 */
public class ListaMovimientosView extends javax.swing.JInternalFrame {
   private MovimientoData movimientoData;
   private DefaultTableModel modelo=new DefaultTableModel(){
     public boolean isCellEditable(int fila,int col){return false;}
};
    public ListaMovimientosView() {
        initComponents();
        movimientoData=new MovimientoData();
        armarLista();
        
    }
private void armarLista(){
    DateTimeFormatter formato=DateTimeFormatter.ofPattern("dd/MM/YYYY");
    
    modelo.addColumn("ID");
    modelo.addColumn("Empleado");
    modelo.addColumn("Herramienta");
    modelo.addColumn("Fecha de pedido");
    modelo.addColumn("Fecha de devolución");
    modelo.addColumn("Cantidad");
    for(Movimiento m: movimientoData.obtenerMovimientos()){
               
        modelo.addRow(new Object[] {
            m.getId_movimiento(),
            m.getEmpleado().toString(),
            m.getHerramienta().toString(),
            m.getFechap().format(formato),
            m.getFechad().format(formato),
            m.getCantidad()});        
        }
    jtMovimientos.setModel(modelo);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMovimientos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jtMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMovimientos);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Devoluciones");

        jButton1.setText("Registrar devolución");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int fila = jtMovimientos.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila.");
        return;
    }

    try {
        int id = (int) jtMovimientos.getValueAt(fila, 0);

        if (jtMovimientos.getValueAt(fila, 4) != null) {
            int choice = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro desea modificar la fecha de devolución por la actual?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
            );

            if (choice == JOptionPane.YES_OPTION) {
                Movimiento m = new Movimiento(
                    id,
                    0,
                    null,
                    null,
                    null,
                    LocalDate.now()  
                );

                movimientoData.registrarDevolucion(m);
                JOptionPane.showMessageDialog(this, "Fecha de devolución registrada");
            }
        } else {
            Movimiento m = new Movimiento(
                id,
                0,
                null,
                null,
                null,
                LocalDate.now()  
            );

            movimientoData.registrarDevolucion(m);
            JOptionPane.showMessageDialog(this, "Fecha de devolución registrada");
        }

        dispose();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La excepción debe ser un número");
    }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMovimientos;
    // End of variables declaration//GEN-END:variables
}
